routes/admin.php
<?php

use App\Http\Controllers\AproposController;
use App\Http\Controllers\CompetenceController;
use App\Http\Controllers\ResumeController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SlideContoller;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('view_admin.index');
});

Route::get('/widgets',function(){
    return view('view_admin.widgets');
})->name('admin.widgets');

Route::get('/generalElement',function(){
    return view('view_admin.elements.generalElement');
})->name('admin.generalElement');

Route::get('/mediaGalerie',function(){
    return view('view_admin.elements.mediaGalerie');
})->name('admin.mediaGalerie');

Route::get('/icons',function(){
    return view('view_admin.elements.icons');
})->name('admin.icons');

Route::get('/invoice',function(){
    return view('view_admin.elements.invoice');
})->name('admin.invoice');

Route::get('/email',function(){
    return view('view_admin.apps.email');
})->name('admin.email');

Route::get('/calander',function(){
    return view('view_admin.apps.calander');
})->name('admin.calander');

Route::get('/tables',function(){
    return view('view_admin.tables');
})->name('admin.tables');

Route::get('/contacts',function(){
    return view('view_admin.contact');
})->name('admin.contacts');

Route::get('/profils',function(){
    return view('view_admin.additionalPage.profils');
})->name('admin.profils');

Route::get('/projets',function(){
    return view('view_admin.additionalPage.projets');
})->name('admin.projets');

Route::get('/login',function(){
    return view('view_admin.additionalPage.login');
})->name('admin.login');

Route::get('/404Page',function(){
    return view('view_admin.additionalPage.404Page');
})->name('admin.404Page');

Route::get('/charts',function(){
    return view('view_admin.charts');
})->name('admin.charts');

Route::get('/settings',function(){
    return view('view_admin.settings');
})->name('admin.settings');

Route::name('admin.')->group(function(){
    Route::controller(SlideContoller::class)->prefix('slide')->name('slide.')->group(function(){
        Route::get('/','index')->name('index');
        Route::post('/','store')->name('store');
        Route::post('update/{slide}','update')->name('update');
        Route::post('active/{slide}','active')->name('is_active');
        Route::delete('delete/{slide}','delete')->name('delete');
    });

    Route::controller(AproposController::class)->prefix('apropos')->name('apropos.')->group(function(){
        Route::get('/','index')->name('index');
        Route::post('/','store')->name('store');
        Route::post('update/{apropos}','update')->name('update');
        Route::delete('delete/{apropos}','delete')->name('delete');
    });

    Route::controller(ResumeController::class)->prefix('resume')->name('resume.')->group(function(){
        Route::get('/','index')->name('index');
        Route::post('/','store')->name('store');
        Route::post('update/{resume}','update')->name('update');
        Route::delete('delete/{resume}','delete')->name('delete');
    });

    Route::controller(ServiceController::class)->prefix('service')->name('service.')->group(function(){
        Route::get('/','index')->name('index');
        
        //formulaire
        Route::get('create/','create')->name('create');
        Route::get('edit/{service}','edit')->name('edit');
        Route::get('show/{service}','show')->name('show');

        //function
        Route::post('/','store')->name('store');
        Route::post('update/{service}','update')->name('update');
        Route::delete('delete/{service}','delete')->name('delete');
    });

    Route::controller(CompetenceController::class)->prefix('competence')->name('competence.')->group(function(){
        Route::get('/','index')->name('index');
        Route::post('/','store')->name('store');
        Route::post('update/{competence}','update')->name('update');
        Route::post('active/{competence}','active')->name('active');
        Route::delete('delete/{competence}','delete')->name('delete');
    });
});

routes/web.php
<?php

use App\Http\Controllers\AccueilController;
use App\Http\Controllers\AvieController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\ServiceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [AccueilController::class,'index'])->name('acceuil');

Route::get('/detailBlog',function(){
    return view('view_site.blog.detailBlog');
 })->name('blog.detailBlog');

 Route::post('addAvie/',[AvieController::class,'store'])->name('avie');
 Route::post('note/',[NoteController::class,'store'])->name('note');

 Route::get('serviceDetails/{service}',[ServiceController::class,'showSite'])->name('service.serviceDetails');

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    use HasFactory;
    protected $guarded = ['_token'];
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Avie;
use App\Models\Note;
use App\Models\Service;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class ServiceController extends Controller
{

    public function index()
    {
        $services = Service::all();
        return view('view_admin.services.index',compact('services'));
    }


    public function create()
    {
        return view('view_admin.services.create');
    }


    public function store(Request $request)
    {
        $media[] = "";
      $data = $request->except('_token','media');
      if($request->hasFile('media')){
        foreach($request->media as $item){
            $media[] = $item->store('service','public');
        }
        $data['media'] = json_encode($media);
      }
      Service::create($data);
      return redirect()->route('admin.service.index')->with('message','service enregistrer avec success !!');
    }


    public function show(Service $service)
    {
        return view('view_admin.services.show',['service'=>$service]);
    }

    public function showSite(Service $service)
    {
        $avies = Avie::where('service_id',$service->id)->get();
        $nbreTemoignage = Avie::where('service_id',$service->id)->count();
        $note = $this->calculNote($service);
        $noteAvie = Note::where('service_id',$service->id)->count();
        return view('view_site.services.serviceDetails',
                    
        [ 'service'=>$service ,
                     'avies'=>$avies,
                        'nbreAvie'=>$nbreTemoignage,
                        'note' => $note,
                        'noteAvie'=>$noteAvie
                    ]);
    }


    public function edit(Service $service)
    {
        return view('view_admin.services.edit',['service'=>$service]);
    }


    public function update(Request $request,Service $service)
    {
        $media[] = "";
      $data = $request->except('_token','media');
      if($request->hasFile('media')){

        foreach(json_decode($service->media) as $item){
            File::delete('storage/'.$item);
        }

        foreach($request->media as $item){

            $media[] = $item->store('service','public');
        }
        $data['media'] = json_encode($media);
      }
      $service->update($data);
      return redirect()->route('admin.service.index')->with('message','service mise à jour avec success !!');
    }


    public function delete(Service $service)
    {
        foreach(json_decode($service->media) as $item){
            File::delete('storage/'.$item);
        }
        $service->delete();
        return redirect()->back()->with('message','le service à été suprimer avec success. ');
    }

    public function calculNote(Service $service){
        $count = Note::where('service_id',$service->id)->count();
        $sum = 0;
        
        if($count!=0){
            $NoteList = Note::where('service_id',$service->id)->get();
            foreach($NoteList as $item){
                $sum = $sum + $item->note;
            }
            $result = $sum/$count;
            return $result;

        }else{
            return 0;
        }
    }
}

resources/views/view_admin/services/create.blade.php
@extends('view_admin.layouts.app')
@section('content')
    <div class="midde_cont">
        <div class="full graph_head">
            <div class="card-header">
                <center><strong class="card-title">Ajouter un Services</strong></center>
            </div>
        </div>
        <form action="{{ route('admin.service.store') }}" method="post" enctype="multipart/form-data" class="form-horizontal">
            @csrf
            <div class="modal-body">
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="text-input" class=" form-control-label">Titre <span class="text-danger">*</span></label>
                    </div>
                    <div class="col-12 col-md-9"><input type="text" id="text-input" name="titre"
                            placeholder="Ajouter un titre" value="{{ old('titre') }}" class="form-control" required>
                        <small class="help-block form-text" style="color:red;">{!! $errors->first('titre', '<p class="help-block" style="color:red">:message</p>') !!}</small>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="summernote" class=" form-control-label">description_1 <span class="text-danger">*</span></label>
                    </div>
                    <div class="col-12 col-md-9"><textarea id="div_editor1" name="description_1" id="summernote" rows="9" placeholder="description..." class="form-control" required>{{ old('description_1') }}</textarea>
                        <small class="help-block form-text" style="color: red">{!! $errors->first('description_1', '<p class="help-block" style="color:red;">:message</p>') !!}</small>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="summernote" class=" form-control-label">description_2 <span class="text-danger">*</span></label>
                    </div>
                    <div class="col-12 col-md-9"><textarea id="div_editor1" name="description_2" id="summernote" rows="9" placeholder="description..." class="form-control">{{ old('description_2') }}</textarea>
                        <small class="help-block form-text" style="color: red">{!! $errors->first('description_2', '<p class="help-block" style="color:red;">:message</p>') !!}</small>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="summernote" class=" form-control-label">description_3 <span class="text-danger">*</span></label>
                    </div>
                    <div class="col-12 col-md-9"><textarea id="div_editor1" name="description_3" id="summernote" rows="9" placeholder="description..." class="form-control">{{ old('description_3') }}</textarea>
                        <small class="help-block form-text" style="color: red">{!! $errors->first('description_3', '<p class="help-block" style="color:red;">:message</p>') !!}</small>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="summernote" class=" form-control-label">description_4 <span class="text-danger">*</span></label>
                    </div>
                    <div class="col-12 col-md-9"><textarea id="div_editor1" name="description_4" id="summernote" rows="9" placeholder="description..." class="form-control">{{ old('description_4') }}</textarea>
                        <small class="help-block form-text" style="color: red">{!! $errors->first('description_4', '<p class="help-block" style="color:red;">:message</p>') !!}</small>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="text-input" class=" form-control-label">Class Icon <span class="text-danger">*</span></label>
                    </div>
                    <div class="col-12 col-md-9"><input type="text" id="text-input" name="code_icon"
                            placeholder="Ajouter un code_icon pour l'acceuil" value="{{ old('code_icon') }}" class="form-control" required>
                        <small class="help-block form-text" style="color:red;">{!! $errors->first('code_icon', '<p class="help-block" style="color:red">:message</p>') !!}</small>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col col-md-3"><label for="file-multiple-input" class=" form-control-label">media<span
                                class="text-danger">*</span></label></div>
                    <div class="col-12 col-md-9"><input type="file" id="file-multiple-input" name="media[]" multiple="" accept="image/*"
                            class="form-control" required>
                        <small class="help-block form-text" style="color: red">{!! $errors->first('media', '<p class="help-block">:message</p>') !!}</small>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href="{{ route('admin.service.index') }}"
                        class="btn btn-warning mb-1"><i class="fa-mail-replay"></i><- Back</a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">annuler</button>
                <button type="submit" class="btn btn-success" onclick="loader_charger(0)"><span
                        id="submit-btn0">Confirmer</span><span class="loader" id="loader0"></span></button>
            </div>
        </form>
    </div>
@endsection

resources/views/view_admin/services/edit.blade.php
@extends('view_admin.layouts.app')
@section('content')
    <div class="midde_cont">
        <div class="full graph_head">
            <div class="card-header">
                <center><strong class="card-title">Mise à Jour d'un Services</strong></center>
            </div>
        </div>
        <form action="{{ route('admin.service.update', $service->id) }}" method="post" enctype="multipart/form-data" class="form-horizontal">
            @csrf
            <div class="modal-body">
                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="text-input" class=" form-control-label">Titre <span class="text-danger">*</span></label>
                    </div>
                    <div class="col-12 col-md-9"><input type="text" id="text-input" name="titre"
                            placeholder="Ajouter un titre" value="{{$service->titre ?? old('titre') }}" class="form-control" required>
                        <small class="help-block form-text" style="color:red;">{!! $errors->first('titre', '<p class="help-block" style="color:red">:message</p>') !!}</small>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="summernote" class=" form-control-label">description_1 <span class="text-danger">*</span></label>
                    </div>
                    <div class="col-12 col-md-9"><textarea id="div_editor1" name="description_1" id="summernote" rows="9" placeholder="description..." class="form-control" required>{{$service->description_1 ?? old('description_1') }}</textarea>
                        <small class="help-block form-text" style="color: red">{!! $errors->first('description_1', '<p class="help-block" style="color:red;">:message</p>') !!}</small>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="summernote" class=" form-control-label">description_2 <span class="text-danger">*</span></label>
                    </div>
                    <div class="col-12 col-md-9"><textarea id="div_editor1" name="description_2" id="summernote" rows="9" placeholder="description..." class="form-control">{{$service->description_2 ?? old('description_2') }}</textarea>
                        <small class="help-block form-text" style="color: red">{!! $errors->first('description_2', '<p class="help-block" style="color:red;">:message</p>') !!}</small>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="summernote" class=" form-control-label">description_3 <span class="text-danger">*</span></label>
                    </div>
                    <div class="col-12 col-md-9"><textarea id="div_editor1" name="description_3" id="summernote" rows="9" placeholder="description..." class="form-control">{{$service->description_3 ?? old('description_3') }}</textarea>
                        <small class="help-block form-text" style="color: red">{!! $errors->first('description_3', '<p class="help-block" style="color:red;">:message</p>') !!}</small>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="summernote" class=" form-control-label">description_4 <span class="text-danger">*</span></label>
                    </div>
                    <div class="col-12 col-md-9"><textarea id="div_editor1" name="description_4" id="summernote" rows="9" placeholder="description..." class="form-control">{{$service->description_4 ?? old('description_4') }}</textarea>
                        <small class="help-block form-text" style="color: red">{!! $errors->first('description_4', '<p class="help-block" style="color:red;">:message</p>') !!}</small>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col col-md-3">
                        <label for="text-input" class=" form-control-label">Class Icon <span class="text-danger">*</span></label>
                    </div>
                    <div class="col-12 col-md-9"><input type="text" id="text-input" name="code_icon"
                            placeholder="Ajouter un code_icon pour l'acceuil" value="{{$service->code_icon ?? old('code_icon') }}" class="form-control" required>
                        <small class="help-block form-text" style="color:red;">{!! $errors->first('code_icon', '<p class="help-block" style="color:red">:message</p>') !!}</small>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col col-md-3"><label for="file-multiple-input" class=" form-control-label">media<span
                                class="text-danger">*</span></label></div>
                    <div class="col-12 col-md-9"><input type="file" id="file-multiple-input" name="media[]" multiple="" accept="image/*"
                            class="form-control" required>
                        <small class="help-block form-text" style="color: red">{!! $errors->first('media', '<p class="help-block">:message</p>') !!}</small>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href="{{ route('admin.service.index') }}"
                        class="btn btn-warning mb-1"><i class="fa-mail-replay"></i><- Back</a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">annuler</button>
                <button type="submit" class="btn btn-success" onclick="loader_charger(0)"><span
                        id="submit-btn0">Confirmer</span><span class="loader" id="loader0"></span></button>
            </div>
        </form>
    </div>
@endsection

resources/views/view_admin/services/index.blade.php
@extends('view_admin.layouts.app')
@section('content')
    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        <h2>Services</h2>
                    </div>
                </div>
            </div>
            <!-- row -->
            <div class="row">
                <!-- table section -->
                <div class="col-md-12">
                    <div class="white_shd full margin_bottom_30">
                        <div class="full graph_head">
                            <div class="card-header">
                                <strong class="card-title">Services</strong>
                                <strong class="card-title" style="float: right"><a
                                        href="{{ route('admin.service.create') }}" class="btn btn-success mb-1"><i
                                            class="fa fa-plus"></i>Ajouter</a></strong>
                            </div>
                        </div>
                        <div class="table_section padding_infor_info">
                            <div class="table-responsive-sm">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>titre</th>
                                            <th>description_1</th>
                                            <th>description_2</th>
                                            <th>description_3</th>
                                            <th>description_4</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($services as $item)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $item->titre }}</td>
                                                <td>{!! Str::limit($item->description_1, 15, '...') !!}</td>
                                                <td>{!! Str::limit($item->description_2, 30, '...') !!}</td>
                                                <td>{!! Str::limit($item->description_3, 30, '...') !!}</td>
                                                <td>{!! Str::limit($item->description_4, 30, '...') !!}</td>
                                                <td class="text-center" style="display: flex">
                                                    <a href="{{ route('admin.service.show', $item->id) }}"
                                                        class="btn btn-info mr-1"><i class="fa fa-eye"></i></a>

                                                    <a href="{{ route('admin.service.edit', $item->id)}}"
                                                        class="btn btn-warning mr-1"><i
                                                            class="fa fa-pencil-square-o"></i></a>

                                                    <button class="btn btn-danger mr-1" title="Supprimer"
                                                        data-toggle="modal" data-target="#delete{{ $item->id }}"><i
                                                            class="fa fa-trash-o"></i></button>
                                                </td>
                                                </td>
                                            </tr>
                                            {{-- @include('view_admin.silde.edit', ['slide' => $item])
                                            @include('view_admin.silde.show', ['slide' => $item])
                                            @include('view_admin.global-modal.active-modal', [
                                                'item' => $item,
                                                'url' => route('admin.slide.is_active', $item->id),
                                            ]) --}}
                                            @include('view_admin.global-modal.delete-modal', [
                                                'id' => $item->id,
                                                'url' => route('admin.service.delete', $item->id),
                                            ])
                                        @empty
                                            <tr>
                                                <td colspan="6" class="text-center">Aucun slide...</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    {{-- @include('view_admin.silde.create') --}}
                </div>
            </div>
            <!-- footer -->
            <div class="container-fluid">
                <div class="footer">
                    <p>Copyright © 2018 Designed by html.design. All rights reserved.</p>
                </div>
            </div>
        </div>
    @endsection

resources/views/view_admin/services/show.blade.php
@extends('view_admin.layouts.app')
@section('content')
    <div class="midde_cont">
        <section class="ftco-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 ftco-animate">
                        <h2 class="mb-3">{{ $service->titre }}</h2>
                        <p>{!! $service->description_1 !!}</p>
                        <p>
                            <img src="{{ asset('storage/'. json_decode($service->media)[1]) }}" alt="" class="img-fluid">
                        </p>
                        <p>{!! $service->description_2 !!}</p>

                        <p>{!! $service->description_3 !!}</p>

                        <p>
                            <img src="{{ asset('storage/'. json_decode($service->media)[2]) }}" alt="" class="img-fluid">
                        </p>
                        <p>{!! $service->description_4 !!}</p>
                    </div>
                    <div class="modal-footer">
                        <a href="{{ route('admin.service.index') }}"
                                class="btn btn-warning mb-1"><i class="fa-mail-replay"></i><- Back</a>
                    </div>

                </div>
            </div>
        </section>
    </div>
@endsection