routes/admin.php
<?php

use App\Http\Controllers\AproposController;
use App\Http\Controllers\CompetenceController;
use App\Http\Controllers\ResumeController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SlideContoller;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('view_admin.index');
});

Route::get('/widgets',function(){
    return view('view_admin.widgets');
})->name('admin.widgets');

Route::get('/generalElement',function(){
    return view('view_admin.elements.generalElement');
})->name('admin.generalElement');

Route::get('/mediaGalerie',function(){
    return view('view_admin.elements.mediaGalerie');
})->name('admin.mediaGalerie');

Route::get('/icons',function(){
    return view('view_admin.elements.icons');
})->name('admin.icons');

Route::get('/invoice',function(){
    return view('view_admin.elements.invoice');
})->name('admin.invoice');

Route::get('/email',function(){
    return view('view_admin.apps.email');
})->name('admin.email');

Route::get('/calander',function(){
    return view('view_admin.apps.calander');
})->name('admin.calander');

Route::get('/tables',function(){
    return view('view_admin.tables');
})->name('admin.tables');

Route::get('/contacts',function(){
    return view('view_admin.contact');
})->name('admin.contacts');

Route::get('/profils',function(){
    return view('view_admin.additionalPage.profils');
})->name('admin.profils');

Route::get('/projets',function(){
    return view('view_admin.additionalPage.projets');
})->name('admin.projets');

Route::get('/login',function(){
    return view('view_admin.additionalPage.login');
})->name('admin.login');

Route::get('/404Page',function(){
    return view('view_admin.additionalPage.404Page');
})->name('admin.404Page');

Route::get('/charts',function(){
    return view('view_admin.charts');
})->name('admin.charts');

Route::get('/settings',function(){
    return view('view_admin.settings');
})->name('admin.settings');

Route::name('admin.')->group(function(){
    Route::controller(SlideContoller::class)->prefix('slide')->name('slide.')->group(function(){
        Route::get('/','index')->name('index');
        Route::post('/','store')->name('store');
        Route::post('update/{slide}','update')->name('update');
        Route::post('active/{slide}','active')->name('is_active');
        Route::delete('delete/{slide}','delete')->name('delete');
    });

    Route::controller(AproposController::class)->prefix('apropos')->name('apropos.')->group(function(){
        Route::get('/','index')->name('index');
        Route::post('/','store')->name('store');
        Route::post('update/{apropos}','update')->name('update');
        Route::delete('delete/{apropos}','delete')->name('delete');
    });

    Route::controller(ResumeController::class)->prefix('resume')->name('resume.')->group(function(){
        Route::get('/','index')->name('index');
        Route::post('/','store')->name('store');
        Route::post('update/{resume}','update')->name('update');
        Route::delete('delete/{resume}','delete')->name('delete');
    });

    Route::controller(ServiceController::class)->prefix('service')->name('service.')->group(function(){
        Route::get('/','index')->name('index');
        
        //formulaire
        Route::get('create/','create')->name('create');
        Route::get('edit/{service}','edit')->name('edit');
        Route::get('show/{service}','show')->name('show');

        //function
        Route::post('/','store')->name('store');
        Route::post('update/{service}','update')->name('update');
        Route::delete('delete/{service}','delete')->name('delete');
    });

    Route::controller(CompetenceController::class)->prefix('competence')->name('competence.')->group(function(){
        Route::get('/','index')->name('index');
        Route::post('/','store')->name('store');
        Route::post('update/{competence}','update')->name('update');
        Route::post('active/{competence}','active')->name('active');
        Route::delete('delete/{competence}','delete')->name('delete');
    });
});

routes/web.php
<?php

use App\Http\Controllers\AccueilController;
use App\Http\Controllers\AvieController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\ServiceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [AccueilController::class,'index'])->name('acceuil');

Route::get('/detailBlog',function(){
    return view('view_site.blog.detailBlog');
 })->name('blog.detailBlog');

 Route::post('addAvie/',[AvieController::class,'store'])->name('avie');
 Route::post('note/',[NoteController::class,'store'])->name('note');

 Route::get('serviceDetails/{service}',[ServiceController::class,'showSite'])->name('service.serviceDetails');

app/Models/Apropos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Apropos extends Model
{
    use HasFactory;
    protected $guarded = ['_token'];
}

app/Http/Controllers/AproposController.php
<?php

namespace App\Http\Controllers;

use App\Models\Apropos;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class AproposController extends Controller
{
    public function index(){
        $apropos = Apropos::all();
        return view('view_admin.apropos.index',compact('apropos'));

    }

    public function store(){

    }

    public function update(Request $request, Apropos $apropos){
        $data = $request->except('_token','photo');
        if(isset($request->photo)){
            File::delete('storage/'.$apropos->photo);
            $data['photo'] = $request->photo->store('Apropos','public');
        }
        $apropos->update($data);

        return redirect()->back()->with('message','la section apropos à été mise à jour !!');
    }

    public function delete( Apropos $apropos){
        File::delete('storage/'.$apropos->photo);
        $apropos->delete();
        return redirect()->back()->with('message','la section apropos à été supprimer');

    }
}

resources/views/view_admin/apropos/edit.blade.php
<div class="modal fade show" id="editApropos{{ $apropos->id }}" tabindex="-1" role="dialog" aria-labelledby="largeModalLabel" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg" style="width: 90%"  role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: rgb(241, 252, 39)">
                <h3 class="modal-title" id="largeModalLabel">Modifier</h3>
                <button type="button" style="float: right" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>

            </div>
            <form action="{{ route('admin.apropos.update',$apropos->id) }}" method="post" enctype="multipart/form-data" class="form-horizontal">
                @csrf
                <div class="modal-body">
                    @include('view_admin.apropos.form')
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">annuler</button>
                    <button type="submit" class="btn btn-success" onclick="loader_charger({{ $apropos->id }})"><span id="submit-btn{{ $apropos->id }}">Confirmer</span><span class="loader" id="loader{{ $apropos->id }}" ></span></button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/view_admin/apropos/form.blade.php
<div class="row form-group">
    <div class="col col-md-3">
        <label for="text-input" class=" form-control-label">Nom <span class="text-danger">*</span></label>
    </div>
    <div class="col-12 col-md-9"><input type="text" id="text-input" name="nom" placeholder="votre nom" value="{{ $apropos->nom?? old('nom') }}"  class="form-control">
        <small class="help-block form-text"  style="color:red;">{!! $errors->first('nom', '<p class="help-block" style="color:red">:message</p>') !!}</small>
    </div>
</div>

<div class="row form-group">
    <div class="col col-md-3">
        <label for="text-input" class=" form-control-label">date_naissance<span class="text-danger">*</span></label>
    </div>
    <div class="col-12 col-md-9"><input type="text" id="text-input" name="date_naissance" placeholder="Sous titre du slide" value="{{ $apropos->date_naissance?? old('date_naissance') }}"  class="form-control">
        <small class="help-block form-text"  style="color:red;">{!! $errors->first('date_naissance', '<p class="help-block" style="color:red">:message</p>') !!}</small>
    </div>
</div>

<div class="row form-group">
    <div class="col col-md-3">
        <label for="text-input" class=" form-control-label">adresse<span class="text-danger">*</span></label>
    </div>
    <div class="col-12 col-md-9"><input type="text" id="text-input" name="adresse" placeholder="Sous titre du slide" value="{{ $apropos->adresse?? old('adresse') }}"  class="form-control">
        <small class="help-block form-text"  style="color:red;">{!! $errors->first('adresse', '<p class="help-block" style="color:red">:message</p>') !!}</small>
    </div>
</div>

<div class="row form-group">
    <div class="col col-md-3">
        <label for="text-input" class=" form-control-label">code_postal<span class="text-danger">*</span></label>
    </div>
    <div class="col-12 col-md-9"><input type="text" id="text-input" name="code_postal" placeholder="Sous titre du slide" value="{{ $apropos->code_postal?? old('code_postal') }}"  class="form-control">
        <small class="help-block form-text"  style="color:red;">{!! $errors->first('code_postal', '<p class="help-block" style="color:red">:message</p>') !!}</small>
    </div>
</div>

<div class="row form-group">
    <div class="col col-md-3">
        <label for="text-input" class=" form-control-label">email<span class="text-danger">*</span></label>
    </div>
    <div class="col-12 col-md-9"><input type="text" id="text-input" name="email" placeholder="Sous titre du slide" value="{{ $apropos->email?? old('email') }}"  class="form-control">
        <small class="help-block form-text"  style="color:red;">{!! $errors->first('email', '<p class="help-block" style="color:red">:message</p>') !!}</small>
    </div>
</div>

<div class="row form-group">
    <div class="col col-md-3">
        <label for="text-input" class=" form-control-label">phone<span class="text-danger">*</span></label>
    </div>
    <div class="col-12 col-md-9"><input type="text" id="text-input" name="phone" placeholder="Sous titre du slide" value="{{ $apropos->phone?? old('phone') }}"  class="form-control">
        <small class="help-block form-text"  style="color:red;">{!! $errors->first('phone', '<p class="help-block" style="color:red">:message</p>') !!}</small>
    </div>
</div>

<div class="row form-group">
    <div class="col col-md-3">
        <label for="text-input" class=" form-control-label">projet compelete<span class="text-danger">*</span></label>
    </div>
    <div class="col-12 col-md-9"><input type="text" id="text-input" name="projet_compelete" placeholder="Sous titre du slide" value="{{ $apropos->projet_compelete?? old('projet_compelete') }}"  class="form-control">
        <small class="help-block form-text"  style="color:red;">{!! $errors->first('projet_compelete', '<p class="help-block" style="color:red">:message</p>') !!}</small>
    </div>
</div>
<div class="row form-group">
        <div class="col col-md-3"><label for="file-multiple-input" class=" form-control-label">Photo<span class="text-danger">*</span></label></div>
        <div class="col-12 col-md-9"><input type="file" id="file-multiple-input"   name="photo"  class="form-control">
            <small class="help-block form-text" style="color: red">{!! $errors->first('photo', '<p class="help-block">:message</p>') !!}</small>
        </div>
</div>

resources/views/view_admin/apropos/index.blade.php
@extends('view_admin.layouts.app')
@section('content')
    <div class="midde_cont">
        <div class="container-fluid">
            <div class="row column_title">
                <div class="col-md-12">
                    <div class="page_title">
                        <h2>Apropos</h2>
                    </div>
                </div>
            </div>
            <!-- row -->
            <div class="row">
                <!-- table section -->
                <div class="col-md-12">
                    <div class="white_shd full margin_bottom_30">
                        <div class="full graph_head">
                            <div class="card-header">
                                <strong class="card-title">Apropos</strong>
                                {{-- <strong class="card-title" style="float: right"><button type="button"
                                        class="btn btn-success mb-1" data-toggle="modal" data-target="#addslide">
                                        <i class="fa fa-plus"></i> Ajouter</button></strong> --}}
                            </div>
                        </div>
                        <div class="table_section padding_infor_info">
                            <div class="table-responsive-sm">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>nom</th>
                                            <th>date_naissance</th>
                                            <th>adresse</th>
                                            <th>code_postal</th>
                                            <th>email</th>
                                            <th>phone</th>
                                            <th>projet compelete</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($apropos as $item)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{!! $item->nom !!}</td>
                                                <td>{!! $item->date_naissance  !!}</td>
                                                <td>{!! $item->adresse  !!}</td>
                                                <td>{!! $item->code_postal  !!}</td>
                                                <td>{!! $item->email  !!}</td>
                                                <td>{!! $item->phone  !!}</td>
                                                <td>{!! $item->projet_compelete  !!}</td>
                                                <td class="text-center" style="display: flex">
                                                    <button class="btn btn-info mr-1" data-toggle="modal"
                                                        data-target="#show{{ $item->id }}"><i
                                                            class="fa fa-eye"></i></button>
                                                    <button class="btn btn-warning mr-1" data-toggle="modal"
                                                        data-target="#editApropos{{ $item->id }}"><i
                                                            class="fa fa-pencil-square-o"></i></button>
                                                </td>
                                                </td>
                                            </tr>
                                            @include('view_admin.apropos.edit', ['apropos' => $item])
                                            @include('view_admin.apropos.show', ['apropos' => $item])
                                        @empty
                                            <tr>
                                                <td colspan="6" class="text-center">Aucun ...</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    {{-- @include('view_admin.apropos.edit') --}}
                </div>
            </div>
            <!-- footer -->
            <div class="container-fluid">
                <div class="footer">
                    <p>Copyright © 2018 Designed by html.design. All rights reserved.</p>
                </div>
            </div>
        </div>
    @endsection

resources/views/view_admin/apropos/show.blade.php
<div class="modal fade show" id="show{{ $apropos->id }}" tabindex="-1" role="dialog" aria-labelledby="largeModalLabel" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg"   role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: rgb(28, 187, 232)">
                <h3 class="modal-title" id="largeModalLabel">Detail</h3>
                <button type="button" style="float: right" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body ">
                <center>
                @if(isset($apropos->photo))
                    <div  class="col-md-4 " >
                    <img   src="{{ asset('storage/'.$apropos->photo) }}" width="200" height="200" >
                    </div>
                @endif
                </center>
                <p class="card-text"  style="display: flex;">  <h4> <strong>nom : </strong> {!! $apropos->nom !!}</h4>   </p><hr>
                <p class="card-text"><h4> <strong>date_naissance: </strong> <h6>{!! $apropos->date_naissance !!}</h6> </h4></p><hr>
                <p class="card-text"><h4> <strong>adresse: </strong> <h6>{!! $apropos->adresse !!}</h6> </h4></p><hr>
                <p class="card-text"><h4> <strong>code postal: </strong> <h6>{!! $apropos->code_postal !!}</h6> </h4></p><hr>
                <p class="card-text"><h4> <strong>email: </strong> <h6>{!! $apropos->email !!}</h6> </h4></p><hr>
                <p class="card-text"><h4> <strong>phone: </strong> <h6>{!! $apropos->phone !!}</h6> </h4></p><hr>
                <p class="card-text"><h4> <strong>projet compelete: </strong> <h6>{!! $apropos->projet_compelete !!}</h6> </h4></p><hr>
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" aria-label="Close" class="btn btn-info">Confirmer</button>
            </div>
        </div>
    </div>
</div>